<a href="https://colab.research.google.com/github/sonichandni/simple-structure-data-binary-classification/blob/master/structure_data_binary_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# CHANGE THIS to your own course materials path
# %cd e:/sundog-consult/Udemy/RecSys/RecSys-Materials/DeepLearningIntro

feature_names =  ['party','handicapped-infants', 'water-project-cost-sharing', 
                    'adoption-of-the-budget-resolution', 'physician-fee-freeze',
                    'el-salvador-aid', 'religious-groups-in-schools',
                    'anti-satellite-test-ban', 'aid-to-nicaraguan-contras',
                    'mx-missle', 'immigration', 'synfuels-corporation-cutback',
                    'education-spending', 'superfund-right-to-sue', 'crime',
                    'duty-free-exports', 'export-administration-act-south-africa']

voting_data = pd.read_csv('house-votes-84.data.txt', na_values=['?'], 
                          names = feature_names)
voting_data.head()

        party  ... export-administration-act-south-africa
0  republican  ...                                      y
1  republican  ...                                    NaN
2    democrat  ...                                      n
3    democrat  ...                                      y
4    democrat  ...                                      y

[5 rows x 17 columns]

In [2]:
voting_data.dropna(inplace=True)
voting_data.describe()

           party  ... export-administration-act-south-africa
count        232  ...                                    232
unique         2  ...                                      2
top     democrat  ...                                      y
freq         124  ...                                    189

[4 rows x 17 columns]

In [0]:
voting_data.replace(('y', 'n'), (1, 0), inplace=True)
voting_data.replace(('democrat', 'republican'), (1, 0), inplace=True)

In [4]:
voting_data.head()

    party  ...  export-administration-act-south-africa
5       1  ...                                       1
8       0  ...                                       1
19      1  ...                                       1
23      1  ...                                       1
25      1  ...                                       1

[5 rows x 17 columns]

In [18]:
all_features = voting_data[feature_names].drop('party', axis=1)
all_classes = voting_data['party']

     handicapped-infants  ...  export-administration-act-south-africa
5                      0  ...                                       1
8                      0  ...                                       1
19                     1  ...                                       1
23                     1  ...                                       1
25                     1  ...                                       1
..                   ...  ...                                     ...
423                    0  ...                                       1
426                    1  ...                                       1
427                    0  ...                                       1
430                    0  ...                                       1
431                    0  ...                                       1

[232 rows x 16 columns]

In [0]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop

In [0]:
x = voting_data.drop(columns=['party'])
y = voting_data['party']

In [0]:
model = Sequential()
model.add(Dense(32, input_dim=16, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [0]:
history = model.fit(x,y,verbose=1)

In [65]:
history.history

{'accuracy': [0.5991379022598267], 'loss': [0.6742959022521973]}